config/routes.rb
Rails.application.routes.draw do
  
  

  

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_for :restaurants, :controllers => { registrations: 'registrations_restaurant' }
  devise_for :clients, :controllers => { registrations: 'registrations' }
  get "/inicio" => "home#index", :as => :index
  get "/acerca-de" => "home#acercade", :as => :acercade
  get "/restaurants/sign_in" => "registrations_restaurant#new", :as => :sign_in
  get "/contactenos" => "home#contacto", :as => :contacto
  get "/home/servicio"
  get '/filtrados' => "home#locales", :as => :locales
  get 'home/buscar'

  root 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/client_address.rb
class ClientAddress < ActiveRecord::Base
end

app/models/dish.rb
class Dish < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/menu.rb
class Menu < ActiveRecord::Base
end

app/models/menu_detail.rb
class MenuDetail < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_attached_file :avatar, 
                    styles: {medium: "300x300>", 
                    thumb: "100x100>" }, 
 default_url: "/images/:style/missing.png"

# Validate presence
validates :avatar, attachment_presence: true, presence: true
# Validate two or more conditions
validates_attachment :avatar, 
 presence: true,
 content_type: 
 {content_type: 
  ["image/jpeg", "image/gif", "image/png"]
 },
 size: { in: 0..1024.kilobytes }

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(restaurant)
    sign_in_url = '/home/locales'
  end
  
  def after_sign_in_path_for(client)
    sign_in_url = '/home/acercade'
  end
  
  def after_sign_in_path_for(administrator)
    sign_in_url = '/home/servicio'
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def acercade
  end

  def servicio
  end

  def contacto
  end
  
  def locales
    @restaurants = Restaurant.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
   
      params.require(:client).permit(:name, :phone, :email, :password, :password_confirmation)
   
  end

  def account_update_params
    params.require(:client).permit(:name, :phone, :email, :password, :password_confirmation, :current_password)
    
  end
end

app/controllers/registrations_restaurant_controller.rb
class RegistrationsRestaurantController < Devise::RegistrationsController

      private

  def sign_up_params
    params.require(:restaurant).permit(:name, :district_id, :telefono, :direccion, :email, :password, :password_confirmation, :avatar)
    
  end

  def account_update_params
    
    params.require(:restaurant).permit(:name, :district_id, :telefono, :direccion, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/registrations_restaurant_helper.rb
module RegistrationsRestaurantHelper
end

app/views/clients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/acercade.html.erb
<div class="container">
    <div class="main">
        <div class="col1">
            <%= render 'shared/busqueda' %>
            <%= render 'shared/ingresocliente' %>
        </div>
        <div id="cuerpo" class="cuerpo">
            <h1 style="margin:0px 20px 10px;">Nosotros</h1>
            <hr>
            <p>
                El ambiente minimalista que se respira acerca al comensal a lo esencial de la gastronomía,
                la sencillez de la belleza y el buen gusto que se complementa con vajilla Philipe des Soliers,
                mobiliario Andreu World, vestuario Lechienerrant, diferentes iluminaciones en cada espacio y
                sala privada para las reuniones más exigentes, un broche de oro a esta propuesta única en la ciudad.
            </p>
            <div>
                <%= image_tag "equipo.png" %>
            </div>
        </div>
    </div>
</div>

app/views/home/contacto.html.erb
<div class="container">
    <div class="main">
        <div class="col1">
            <%= render 'shared/busqueda' %>
            <%= render 'shared/ingresocliente' %>
        </div>
        <div id="cuerpo" class="cuerpo">
            <h1 style="margin:0px 20px 10px;">Contáctenos</h1>
            <hr>
            <div>
                <div id="dialogo" class="modal-box">
                    <header style="width:303px;">
                        <a href="#" class="js-modal-close close">×</a>
                        <h3>Mensaje</h3>
                    </header>
                    <div class="modal-body">
                        <p>Mensaje enviado.</p>
                    </div>
                    <footer><a href="#" class="js-modal-close botonahref">Cerrar</a></footer>
                </div>
                <form>
                    <div style="  margin: 15px auto;width: 450px;">
                        <table width="100%" cellspacing="15">
                            <tr>
                                <td width="15%">
                                    <label for="">Nombre</label>
                                </td>     
                                <td width="85%">
                                    <input size="65" type="text" style="width: 330px;" name="" value=""/>
                                </td> 
                            </tr>
                            <tr>
                                <td>
                                    <label for="">Correo</label>
                                </td>     
                                <td>
                                    <input size="65" type="text" style="width: 330px;" name="" value=""/>
                                </td> 
                            </tr>
                            <tr>
                                <td>
                                    <label for="">Teléfono</label>
                                </td>     
                                <td>
                                    <input size="30" type="text" style="width: 180px;" name="" value=""/>
                                </td> 
                            </tr>
                            <tr style="vertical-align:top;">
                                <td>
                                    <label for="">Mensaje</label>
                                </td>     
                                <td>
                                    <textarea cols="15" rows="5"></textarea>
                                </td> 
                            </tr>
                        </table>
                    </div>
                    <div>
                        <div style="margin-bottom: 10px;">
                            <table width="40%" style="margin:auto;">
                                <tr>
                                    <td width="120px" height="35px" align="right">
                                        <a href="#" class="js-open-modal botonahref" data-modal-id="dialogo" style="width: 100px;">Grabar</a>
                                    </td>
                                    <td width="10%"> </td>
                                    <td width="120px" height="35px" align="right">
                                        <%= link_to 'Limpiar', '#', onclick: 'clearForm(this.form);', class: "link_to" %>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </form>
                <input type="button" name="" style="width: 150px;margin-left: 150px;" value="Mostrar ubicación" onclick="getLocation()"/>
                <div id="map" style="padding-bottom: 15px;text-align: center;"></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function(){
        var appendthis = ("<div class='modal-overlay js-modal-close'></div>");
        $('a[data-modal-id]').click(function(e) {
    		e.preventDefault();
            $("body").append(appendthis);
            $(".modal-overlay").fadeTo(500, 0.7);
            //$(".js-modalbox").fadeIn(500);
        	var modalBox = $(this).attr('data-modal-id');
        	$('#'+modalBox).fadeIn($(this).data());
        });  
        	
        $(".js-modal-close, .modal-overlay").click(function() {
            $(".modal-box, .modal-overlay").fadeOut(500, function() {
                $(".modal-overlay").remove();
            });
        });
        
        $(window).resize(function() {
            $(".modal-box").css({
                top: ($(window).height() - $(".modal-box").outerHeight()) / 2,
                left: ($(window).width() - $(".modal-box").outerWidth()) / 2
            });
        });
        
        $(window).resize();
    });
</script>

app/views/home/index.html.erb
<div class="container">
    <div class="main">
        <div class="col1">
            <%= render 'shared/busqueda' %>
            <%= render 'shared/ingresocliente' %>
        </div>
        <div class="col2">
            <h1>Bienvenido</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <div class="contFood">
                <div class="contBloq">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food1</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food2</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
                <div class="contBloq">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food3</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food4</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
                <div class="contBloq noBorBot">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food5</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food6</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/locales.html.erb
<div class="container">
    <div class="main">
        <div class="col1">
            <%= render 'home/busqueda' %>

            <%= render 'home/ingresocliente' %>
 
        </div>
        <div class="col2">
            <h1>Restaurantes encontrados</h1>    
            <% @restaurants.each do |local| %>
                <tr>
                    <h2><a href="local.html"><%= local.name %></a></h2>
                    <p>Dirección: <%= local.direccion %></p> 
                    <p>Teléfono: <%= local.telefono %></p>
                    <p>Correo electrónico: <%= local.email %></p>
                    <%= image_tag local.avatar.url %>
                    <a href="local.html" class="verMenu">Ver menú</a>
                    <p>   </p>
                    <p>   </p>
                </tr>
            <% end %>
                
        </div>
    </div>
</div>

app/views/home/servicio.html.erb
<h1>Home#servicio</h1>
<p>Find me in app/views/home/servicio.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>MENÚ EXPRESS</title>
    <%= stylesheet_link_tag    'style', media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'normalize', media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    'application', media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
        <script type="text/javascript">

            var doc=document.getElementById("localizacion");
            function getLocation()
            {
                if (navigator.geolocation)
                {
                    navigator.geolocation.getCurrentPosition(showPosition,showError);
                }
            }
        
            function showPosition(position)
            {
                var latlon=position.coords.latitude+","+position.coords.longitude;
        
                var img_url="http://maps.googleapis.com/maps/api/staticmap?center="
                +latlon+"&zoom=14&size=400x300&sensor=false";
                document.getElementById("map").innerHTML="<img src='"+img_url+"'>";
            }
        
            function showError(error)
            {
                switch(error.code) 
                {
                case error.PERMISSION_DENIED:
                    doc.innerHTML="Request for Geolocation denied by the user."
                    break;
                case error.POSITION_UNAVAILABLE:
                    doc.innerHTML="Unavailable location information."
                    break;
                case error.TIMEOUT:
                    doc.innerHTML="Location request timed out."
                    break;
                case error.UNKNOWN_ERROR:
                    doc.innerHTML="UNKNOWN_ERROR."
                    break;
                }
            }
        </script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<header>
    <nav class="menuPrin">
      <div class="conPerfil"><%= link_to "Cerrar sesión", destroy_client_session_path, method: :delete %></div>
      <ul>
        <li><%= link_to "INICIO", :index %></li>
        <li><%= link_to "LOGIN RESTAURANTES", :sign_in %></li>
        <li class="logo"><%= link_to image_tag('logo.png'), root_path %></li>
        <li><%= link_to "ACERCA DE", :acercade %></li>
        <li><%= link_to "CONTACTENOS", :contacto %></li>
    </nav>
</header>
    <%= yield %>
<footer>
    <ul>
        <li style="margin: 80px 62px 10px;"><a href="index.html" style="color: #54671E;">INICIO</a></li>
        <li style="margin: 80px 62px 10px;"><a href="acerca-de.html" style="color: #54671E;">LOGIN RESTAURANTE</a></li>
        <li style="margin: 80px 62px 10px;"><a href="servicio.html" style="color: #54671E;">ACERCA DE</a></li>
        <li style="margin: 80px 62px 10px;"><a href="contactenos.html" style="color: #54671E;">CONTACTENOS</a></li>
    </ul>
</footer>
  </body>
</html>

app/views/registrations_restaurant/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/registrations_restaurant/new.html.erb
<h2>Registro de Locales</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>
  
  <div class="field">
    <%= f.label :'Nombre' %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :'Teléfono' %><br />
    <%= f.text_field :telefono %>
  </div>
  
  <div class="field">
    <%= f.label :'Dirección' %><br />
    <%= f.text_field :direccion %>
  </div>
  
  <div class="field">
    <%= f.label :'Distrito' %><br />
    <%= f.text_field :district_id %>
  </div>
  
  <div class="field">
    <%= f.label :'Imagen' %><br />
    <%= f.file_field :avatar %>
  </div>
  
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "restaurants/shared/links" %>

app/views/restaurants/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shared/_busqueda.html.erb
<h3>Búsqueda por Distrito</h3>

<form class="busqueda">
    <label for="">DEPARTAMENTO</label>
    <input type="text" name="" value="Lima" disabled/>
    <label for="">DISTRITO</label>
    <%= select("post", "person_id", District.all.collect {|p| [ p.no_distrito, p.district_id ] }, {prompt: 'Selecciona Distrito'}) %>
    <input type="button" value="Buscar" name="" onclick="location.href = 'locales.html'" style="margin-right: 5px;"/>
</form>

app/views/shared/_footer.html.erb
<div class="footer">
    <ul>
        <li><a href="index.html">INICIO</a></li>
        <li><a href="acerca-de.html">ACERCA DE</a></li>
        <li><a href="servicio.html">SERVICIO</a></li>
        <li><a href="contactenos.html">CONTACTENOS</a></li>
    </ul>
</div>

app/views/shared/_header.html.erb
<header>
    <nav style="position: relative;">
        <div class="linkusuario">
            <%= link_to '>> Nombre Usuario', '', :style => "position: absolute;" %>
        </div>
        <ul>
            <li><%= link_to "INICIO", :index %></li>
            <li><%= link_to "ACERCA DE", :sign_in %></li>
            <li style="margin-top: 10px;"><%= link_to (image_tag "logo.png", {:style => "padding-top: 5px;"}), root_path %></li>
            <li><%= link_to "SERVICIO", :acercade %></li>
            <li><%= link_to "CONTACTENOS", :contacto %></li>
        </ul>
    </nav>
</header>

app/views/shared/_ingresocliente.html.erb
<h3>Ingreso de Cliente</h3>

<%= form_for(:client, :url => session_path(:client), html: {class: "busqueda"}) do |f| %>
  <div class="field">
    <%= f.label :'Correo' %>
    <%= f.email_field :email, autofocus: true, :class=> "inputtext", :style=> "width:172px" %>
  </div>

  <div class="field">
    <%= f.label :'Contraseña' %>
    <%= f.password_field :password, autocomplete: "off", :class=> "inputtext", :style=> "width:172px" %>
  </div>

  
    <div class="field">
      <%= f.check_box :remember_me, :style => "float:left;" %> <%= f.label :'remember_me' %>
    </div>
  

  <div class="actions">
    <%= f.submit "Ingresar", :class=> "button", :style =>  "margin-right: 5px;" %>
  </div>
<% end %>

app/views/temporal/acercade.html.erb
<div class="container">
            <div class="main">
                <div class="col1">
                    <form class="busqueda">
                        <label for="">DEPARTAMENTO</label>
                        <input type="text" name="" value="Lima"/>
                        <label for="">DISTRITO</label>
                        <select>
                            <option>Selecciona distrito</option>
                            <option>San Isidro</option>
                            <option>La Victoria</option>
                        </select>
                        <input type="button" value="Buscar" name=""/>
                    </form>
                    <form class="registro">
                        <h3>INICIAR SESIÓN</h3>
                        <div class="contReg">
                        <label for="">USUARIO</label>
                        <input type="text" name="" value=""/>
                        <label for="">CONTRASEÑA</label>
                        <input type="text" name="" value=""/>
                        <input type="button" value="Ingresar" name=""/>
                        <input type="button" value="Registrate" name=""/>
                        </div>
                    </form>
                </div>
                <div class="col2">
                    <h1>Acerca de</h1>
                    <p>At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p><br><br><br><br><br><br><br><br><br>
                </div>
            </div>
        </div>

app/views/temporal/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>MENÚ EXPRESS</title>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
    <nav class="menuPrin">
      <div class="conPerfil"><%= link_to "Cerrar sesión", destroy_client_session_path, method: :delete %></div>
      <ul>
        <li><a href="home/index">INICIO</a></li>
        <li><a href="home/acercade">ACERCA DE</a></li>
        <li class="logo"><a href="home/index"><%= image_tag "logo.png" %></a></li>
        <li><a href="home/servicio">SERVICIO</a></a></li>
        <li><a href="home/contactenos">CONTACTENOS</a></a></li>
      </ul>
    </nav>
</header>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

<footer>
    <ul>
        <li><a href="index.html">Inicio</a></li>
        <li><a href="acerca-de.html">Acerca de</a></li>
        <li><a href="servicio.html">Servicio</a></li>
        <li><a href="contactenos.html">Contáctenos</a></li>
    </ul>
</footer>

</body>
</html>

app/views/temporal/index.html.erb
<div class="container">
    <div class="main">
        <div class="col1">
            <form class="busqueda">
                <label for="">DEPARTAMENTO</label>
                <input type="text" name="" value="Lima"/>
                <label for="">DISTRITO</label>
                
                <%= select("post", "person_id", District.all.collect {|p| [ p.no_distrito, p.district_id ] }, {prompt: 'Selecciona Distrito'}) %>
                <input type="button" value="Buscar" name="" onclick="location.href = 'locales.html'"/>
            <%= form_for(:client, :url => session_path(:client)) do |f| %>
  <div class="field">
    <%= f.label :'Correo' %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :'Contraseña' %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  

  <div class="actions">
    <%= f.submit "Ingresar" %>
  </div>
<% end %>


 
        </div>
        <div class="col2">
            <h1>Bienvenido</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            <div class="contFood">
                <div class="contBloq">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food1</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food2</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
                <div class="contBloq">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food3</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food4</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
                <div class="contBloq noBorBot">
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food1.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food5</span><span class="tex2">S/.13.00</span></p>
                    </div>
                    <div class="food">
                        <div><a href="local.html"><%= image_tag "food/food2.jpg", width:"100%" %></a></div>
                        <p><span class="tex1">Food6</span><span class="tex2">S/.10.00</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>